README.md
I added my project to README.md.
=> amirhallaji added

README.md
I added my project to README.md
=> Rasoul Akhondi

README.md
=> add name and project url

README.md
linked Repository will be updated and improved before deadline thank you for your patience
=> Added name and link to README.MD

README.md
Arya Parvizi's [Project URL](https://github.com/ph504/ai-computer-assignment1-eight-puzzle#eight-puzzle-ai) was added.
=> added name and project URL

README.md
=> Mohammad Hossein Heydarzadeh

README.md
=> some changes in README

README.md
added "- dorreen rostami [project](https://github.com/DorreenRostami/SBU_elasticSearch)" to "README.md" because of the second question in our first IE exercise
=> added my name and project link

README.md
I added my name and my CI project link to readme.md for  IE exercise 1.
I also created [NNargesNN](https://github.com/NNargesNN/NNargesNN)  repository .
=> Narges Ghasemi : added my name and project link to readme

README.md
I added my info to the README file
ali moghimi 96243085 - Internet Engineering course of  99-00
=> ali moghimi added his info to the README file -  please Update/merge your README file

README.md
dear roozbeh, please accept my pull request🙂
Alireza Rashidi
96243097
=> add Alireza Rashidi, edited readme.md.

README.md
the last line of your README.md file has been deleted.
my name and my project's link has been added instead.
=> clone committed

README.md
I didn't remove the line related to Roozbeh Sharifinasab and added my information to README.md as a new element of list.
=> Add Peyman Alavi to README.md

README.md
=> add Ali Rezasoltani project

README.md
I added my name and repository link to the readme file.
shaghayegh fathi 97243096
=> added my info to readme

README.md
=> name and project link added to readme

README.md
=> repository of githup

README.md
=> for a few more score :)

README.md
add my name to the readme file
=> my name (Lotfizade) added to the file

README.md
please add my name and project link.
=> ghazal kalhori

README.md
add Hadi Moradi and add project link to README
=> add Hadi Moradi to README

README.md
=> Adding my project to the list

README.md
=> Mojtaba Torabi

README.md
here is some comments , as if I'm contributing
=> sample project added for IE hw

README.md
added arad hesadi to README.md
=> added my name to the list (Arad Hesadi)

README.md
=> Mohammadmehdi Khan is added to list

README.md
Added my name and my link - Mesmol
=> //Name and link added

README.md
I have added my project link and my name.
=> Mohammad Reza Eskini / Readme file / Added my details

README.md
=> I'm Kosar Dastbaz and add mine.

README.md
Hello,I'm Mohammad hossein mosalman. IE student
=> Pull Request from Mohammad Hossein Mosalman

README.md
For 2nd part of Question 2 of EX1, IE Spring 1401
=> Mh.Arsalan Added his own line to readme file

README.md
name and project link added (AmirHossein Advari)
=> AmirHossein Advari Added.

README.md
=> project added - mahsa bahri

README.md
This might be a duplicate since i cant see my pull request.
Might have forgotten to click on the create button.
=> Added Keivan Banan project

README.md
Hi bro, plz merge this stuff, thx.
=> Add a github project url of Ehsan Jafari Moghadam

README.md
=> Erfan Nikooee project added Readme.md

README.md
I'm just doing the assignments :)
=> Added my information to the README file

README.md
=> my project added
